# Generated by Django 6.0.4 on 2026-09-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslog',
            options={'ordering': ['-occurred_at'], 'verbose_name': "Journal d'accès", 'verbose_name_plural': "Journaux d'accès"},
        ),
    ]
