# Generated by Django 6.0.4 on 2026-06-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN_CA', "Administrateur / Conseil d'administration"), ('ADMIN_INTEGRATION', 'Administrateur intégrations'), ('DG_GROUP', 'Directeur général groupe'), ('CODIR', 'Membre du CODIR'), ('DAF', 'Directeur administratif & financier'), ('DRH', 'Directeur des ressources humaines'), ('DIR_OPS', 'Directeur opérationnel'), ('RESP_METIER', 'Responsable métier'), ('READER', 'Lecteur')], default='READER', max_length=20),
        ),
    ]
