import type * as React from "react";

import {
  Bell,
  Briefcase,
  Building,
  Calculator,
  Calendar,
  Cart,
  ChartPie,
  CheckCircle,
  Cog,
  DollarCircle,
  FileText,
  Grid,
  Help,
  Layers,
  Network,
  Receipt,
  Shield,
  Target,
  User,
  Users,
  Wallet,
} from "@/components/overview/icons";

export interface ModuleKpi {
  label: string;
  value: string;
  gauge: number;
  color: string;
  delta: string;
  up: boolean;
  source?: string;
}

export type ModuleKind = "default" | "notifications" | "settings" | "profile" | "help" | "ai";
export type ModuleChartType = "line" | "bar" | "pie" | "funnel" | "gantt" | "heatmap" | "radar";

export interface ModuleChart {
  title: string;
  subtitle: string;
  type: ModuleChartType;
  source: string;
}

export interface ModuleRow {
  title: string;
  detail: string;
  accent: string;
}

export interface ModuleSection {
  title: string;
  subtitle: string;
  source: string;
  chart: ModuleChart;
  rows: ModuleRow[];
}

export interface ModuleDef {
  key: string;
  title: string;
  subtitle: string;
  status: string;
  accent: string;
  icon: React.ReactNode;
  kind: ModuleKind;
  source: string;
  kpis?: ModuleKpi[];
  rows?: ModuleRow[];
  sections?: ModuleSection[];
  home?: boolean;
}

const ICON_SIZE = { width: 30, height: 30 };
const COLORS = ["#416FF4", "#42BFA0", "#D92B55", "#FF8735", "#8A63D2"];
const MART_STATUS = "Mart à connecter — aucune donnée inventée";

function metricKpis(source: string, labels: string[]): ModuleKpi[] {
  return labels.map((label, index) => ({
    label,
    value: "N/D",
    gauge: 8,
    color: COLORS[index % COLORS.length],
    delta: "mart à connecter",
    up: false,
    source,
  }));
}

function rows(items: string[], source: string): ModuleRow[] {
  return items.map((title, index) => ({
    title,
    detail: `${source} · donnée attendue du Data Warehouse`,
    accent: COLORS[index % COLORS.length],
  }));
}

function chart(title: string, subtitle: string, type: ModuleChartType, source: string): ModuleChart {
  return { title, subtitle, type, source };
}

function section(
  title: string,
  subtitle: string,
  source: string,
  chartType: ModuleChartType,
  rowItems: string[],
): ModuleSection {
  return {
    title,
    subtitle,
    source,
    chart: chart(title, subtitle, chartType, source),
    rows: rows(rowItems, source),
  };
}

export const MODULES: Record<string, ModuleDef> = {
  executive: {
    key: "executive",
    title: "Executive Overview",
    subtitle: "Vue DG consolidée : patrimoine, programmes, ventes, cash, ROI et risques.",
    status: MART_STATUS,
    accent: "#FF8735",
    icon: <Target {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_executive_kpi",
    home: true,
    kpis: metricKpis("mart.real_estate_executive_kpi", [
      "Valeur totale du patrimoine",
      "Nombre total de programmes",
      "Programmes actifs",
      "Programmes terminés",
      "Programmes en retard",
      "Chiffre d'affaires",
      "Résultat net",
      "Cash disponible",
      "Budget consommé",
      "ROI global",
      "Taux de commercialisation",
      "Taux d'occupation",
      "Valeur des stocks",
      "Valeur foncière",
      "Nombre de clients",
      "Nombre de ventes",
      "Nombre de réservations",
    ]),
    sections: [
      section("Evolution CA", "Tendance mensuelle du chiffre d'affaires", "mart.real_estate_revenue_monthly", "line", ["CA mensuel", "Objectif", "Ecart"]),
      section("Evolution ventes", "Ventes, réservations et annulations", "mart.real_estate_sales_monthly", "bar", ["Ventes", "Réservations", "Annulations"]),
      section("Evolution marge", "Marge brute et résultat net", "mart.real_estate_margin_monthly", "line", ["Marge", "Résultat net", "EBITDA"]),
      section("Evolution cash", "Encaissements, décaissements et cash net", "mart.real_estate_cashflow_monthly", "line", ["Encaissements", "Décaissements", "Cash net"]),
      section("Evolution construction", "Avancement physique consolidé", "mart.real_estate_construction_progress", "bar", ["Gros oeuvre", "VRD", "Finitions"]),
    ],
  },
  portfolio: {
    key: "portfolio",
    title: "Portfolio Immobilier",
    subtitle: "Terrains, programmes, résidences, immeubles, villas, appartements et actifs exploités.",
    status: MART_STATUS,
    accent: "#416FF4",
    icon: <Briefcase {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_portfolio_kpi",
    home: true,
    kpis: metricKpis("mart.real_estate_portfolio_kpi", [
      "Nombre d'actifs",
      "Valeur portefeuille",
      "Surface totale",
      "Occupation",
      "Disponibilité",
      "Rentabilité",
      "Répartition géographique",
    ]),
    sections: [
      section("Répartition par typologie", "Terrains, bureaux, villas, appartements et entrepôts", "mart.real_estate_asset_mix", "pie", ["Terrains", "Villas", "Appartements", "Bureaux", "Entrepôts"]),
      section("Répartition géographique", "Pays, ville, commune et quartier", "mart.real_estate_geo_distribution", "heatmap", ["Pays", "Ville", "Commune", "Quartier"]),
    ],
  },
  land: {
    key: "land",
    title: "Gouvernance Foncière",
    subtitle: "Titres fonciers, hypothèques, surfaces disponibles, documents cadastraux et échéances.",
    status: MART_STATUS,
    accent: "#42BFA0",
    icon: <Layers {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_land_kpi",
    home: true,
    kpis: metricKpis("mart.real_estate_land_kpi", [
      "Nombre de terrains",
      "Valeur foncière",
      "Titres fonciers",
      "Titres en attente",
      "Hypothèques",
      "Valeur hypothécaire",
      "Surface totale",
      "Surface disponible",
      "Surface exploitée",
      "Surface constructible",
      "Documents cadastraux",
      "Expiration documents",
    ]),
    sections: [
      section("Surfaces foncières", "Exploité, disponible, constructible", "mart.real_estate_land_surface", "bar", ["Surface disponible", "Surface exploitée", "Surface constructible"]),
      section("Documents & échéances", "Titres, cadastre, hypothèques", "mart.real_estate_land_documents", "gantt", ["Titre foncier", "Cadastre", "Hypothèque", "Renouvellement"]),
    ],
  },
  construction: {
    key: "construction",
    title: "Gouvernance Construction",
    subtitle: "Budget, coût réel, retard, qualité, livraison et indice de performance par chantier.",
    status: MART_STATUS,
    accent: "#FF8735",
    icon: <Building {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_construction_kpi",
    home: true,
    kpis: metricKpis("mart.real_estate_construction_kpi", [
      "Budget",
      "Coût réel",
      "Coût restant",
      "Avancement",
      "Retard",
      "Qualité",
      "Date livraison",
      "Indice performance",
    ]),
    sections: [
      section("Courbe S", "Planifié vs réalisé", "mart.real_estate_s_curve", "line", ["Planifié", "Réalisé", "Ecart"]),
      section("Burn Rate", "Consommation budgétaire par période", "mart.real_estate_burn_rate", "bar", ["Budget consommé", "Coût restant", "Ecart"]),
      section("Planning Gantt", "Terrassement, fondation, gros œuvre, second œuvre, VRD, finitions, réception", "mart.real_estate_project_schedule", "gantt", ["Terrassement", "Fondation", "Gros œuvre", "Second œuvre", "VRD", "Finitions", "Réception"]),
      section("Evolution Budget", "Budget initial, révisé et réel", "mart.real_estate_budget_evolution", "line", ["Budget initial", "Budget révisé", "Coût réel"]),
    ],
  },
  vrd: {
    key: "vrd",
    title: "VRD",
    subtitle: "Voirie, électricité, drainage, assainissement, télécom, eau potable et espaces verts.",
    status: MART_STATUS,
    accent: "#2BB7A3",
    icon: <Network {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_vrd_kpi",
    home: true,
    kpis: metricKpis("mart.real_estate_vrd_kpi", ["Avancement", "Budget", "Qualité", "Retards", "Incidents"]),
    sections: [
      section("Avancement VRD", "Comparatif par lot technique", "mart.real_estate_vrd_progress", "bar", ["Voirie", "Electricité", "Drainage", "Assainissement", "Télécom", "Eau potable", "Espaces verts"]),
      section("Incidents VRD", "Retards, qualité et incidents ouverts", "mart.real_estate_vrd_incidents", "radar", ["Retards", "Qualité", "Incidents", "Budget", "Réception"]),
    ],
  },
  commercialisation: {
    key: "commercialisation",
    title: "Commercialisation",
    subtitle: "Leads, prospects, réservations, contrats, ventes, livraisons et annulations.",
    status: MART_STATUS,
    accent: "#7A5AF8",
    icon: <Target {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_sales_kpi",
    home: true,
    kpis: metricKpis("mart.real_estate_sales_kpi", [
      "Leads",
      "Prospects",
      "Réservations",
      "Contrats",
      "Ventes",
      "Livraisons",
      "Annulations",
      "Taux conversion",
      "Lots disponibles",
      "Lots réservés",
      "Lots vendus",
      "Lots livrés",
      "CA commercial",
      "Objectifs commerciaux",
      "Top commerciaux",
    ]),
    sections: [
      section("Pipeline commercial", "Leads vers ventes signées", "mart.real_estate_sales_pipeline", "funnel", ["Leads", "Prospects", "Réservations", "Contrats", "Ventes"]),
      section("Evolution ventes", "Ventes et réservations mensuelles", "mart.real_estate_sales_evolution", "line", ["Réservations", "Ventes", "Annulations"]),
      section("Carte ventes", "Répartition géographique des ventes", "mart.real_estate_sales_map", "heatmap", ["Pays", "Ville", "Commune", "Quartier"]),
    ],
  },
  rental: {
    key: "rental",
    title: "Gestion Locative",
    subtitle: "Biens loués, vacance, loyers, impayés, baux et renouvellements.",
    status: MART_STATUS,
    accent: "#416FF4",
    icon: <Receipt {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_rental_kpi",
    home: true,
    kpis: metricKpis("mart.real_estate_rental_kpi", ["Biens loués", "Biens vacants", "Taux occupation", "Loyers", "Impayés", "Baux", "Renouvellements", "Expiration contrats", "Revenus locatifs", "Rentabilité"]),
    sections: [
      section("Occupation locative", "Occupation, vacance et renouvellements", "mart.real_estate_rental_occupancy", "bar", ["Loués", "Vacants", "Renouvellements"]),
      section("Revenus locatifs", "Loyers, impayés et rentabilité", "mart.real_estate_rental_income", "line", ["Loyers", "Impayés", "Rentabilité"]),
    ],
  },
  finance: {
    key: "finance",
    title: "Finances",
    subtitle: "Connexion Odoo Comptabilité : budget, cash flow, charges, produits et résultat.",
    status: MART_STATUS,
    accent: "#42BFA0",
    icon: <Wallet {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_finance_kpi",
    home: true,
    kpis: metricKpis("mart.real_estate_finance_kpi", ["Budget", "Budget consommé", "Budget restant", "Encaissements", "Décaissements", "Cash Flow", "Charges", "Produits", "Marge", "EBITDA", "Résultat net", "Résultat opérationnel"]),
    sections: [
      section("Evolution trésorerie", "Cash in, cash out et cash net", "mart.real_estate_treasury_evolution", "line", ["Encaissements", "Décaissements", "Cash net"]),
      section("Répartition dépenses", "Dépenses par nature et centre de coût", "mart.real_estate_expense_distribution", "pie", ["Construction", "Commercial", "Foncier", "Maintenance"]),
      section("Prévisions finance", "Projection cash et marge", "analytics.real_estate_finance_forecast", "line", ["Prévision 30j", "Prévision 60j", "Prévision 90j"]),
    ],
  },
  treasury: {
    key: "treasury",
    title: "Trésorerie",
    subtitle: "Cash disponible, flux entrants/sortants, engagements et projection 90 jours.",
    status: MART_STATUS,
    accent: "#2D74E0",
    icon: <DollarCircle {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_treasury_kpi",
    home: true,
    kpis: metricKpis("mart.real_estate_treasury_kpi", ["Cash disponible", "Cash engagé", "Flux entrants", "Flux sortants", "Cash net", "Projection 90 jours"]),
    sections: [
      section("Cash Flow", "Flux de trésorerie opérationnels", "mart.real_estate_cashflow_daily", "line", ["Cash in", "Cash out", "Net"]),
      section("Prévision 90 jours", "Projection ancrée sur l'EDW", "analytics.real_estate_cash_forecast", "line", ["J+30", "J+60", "J+90"]),
    ],
  },
  accounting: {
    key: "accounting",
    title: "Comptabilité",
    subtitle: "Balance, grand livre, journal, créances, dettes, TVA, factures et échéances.",
    status: MART_STATUS,
    accent: "#E08A1E",
    icon: <Calculator {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_accounting_kpi",
    home: true,
    kpis: metricKpis("mart.real_estate_accounting_kpi", ["Balance", "Grand Livre", "Journal", "Créances", "Dettes", "TVA", "Factures", "Recouvrements", "Echéances"]),
    sections: [
      section("Créances & dettes", "Aging client/fournisseur", "mart.real_estate_accounting_aging", "bar", ["0-30j", "31-60j", "61-90j", "+90j"]),
      section("TVA & échéances", "TVA collectée, déductible et échéances", "mart.real_estate_tax_schedule", "gantt", ["TVA", "Factures", "Recouvrements", "Echéances"]),
    ],
  },
  inventory: {
    key: "inventory",
    title: "Stocks",
    subtitle: "Connexion Odoo Stock : valeur, rotation, ruptures, consommation, inventaires et matériaux critiques.",
    status: MART_STATUS,
    accent: "#2BB7A3",
    icon: <Cart {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_inventory_kpi",
    home: true,
    kpis: metricKpis("mart.real_estate_inventory_kpi", ["Valeur stock", "Rotation", "Ruptures", "Consommation", "Entrées", "Sorties", "Inventaires", "Matériaux critiques", "Equipements", "Outillage"]),
    sections: [
      section("Rotation stock", "Entrées, sorties et consommation", "mart.real_estate_inventory_rotation", "bar", ["Entrées", "Sorties", "Consommation"]),
      section("Matériaux critiques", "Ruptures et seuils minimum", "mart.real_estate_critical_materials", "radar", ["Ciment", "Fer", "Carrelage", "Peinture", "VRD"]),
    ],
  },
  maintenance: {
    key: "maintenance",
    title: "Maintenance",
    subtitle: "Engins, matériels, véhicules, ascenseurs, groupes électrogènes et climatisation.",
    status: MART_STATUS,
    accent: "#5B8DEF",
    icon: <Cog {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_maintenance_kpi",
    home: true,
    kpis: metricKpis("mart.real_estate_maintenance_kpi", ["Disponibilité", "Maintenance préventive", "Maintenance corrective", "Temps arrêt", "Coût maintenance"]),
    sections: [
      section("Disponibilité équipements", "Disponibilité par famille d'actif", "mart.real_estate_equipment_availability", "bar", ["Engins", "Véhicules", "Ascenseurs", "Groupes", "Climatisation"]),
      section("Coûts maintenance", "Préventif vs correctif", "mart.real_estate_maintenance_cost", "line", ["Préventif", "Correctif", "Temps arrêt"]),
    ],
  },
  "chantier-resources": {
    key: "chantier-resources",
    title: "Ressources Chantier",
    subtitle: "Connexion RH et K-Shield : présence temps réel, productivité, heures, coût MO et pointage RFID.",
    status: MART_STATUS,
    accent: "#8A63D2",
    icon: <Users {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_site_resources_kpi",
    home: true,
    kpis: metricKpis("mart.real_estate_site_resources_kpi", ["Ouvriers présents", "Présence temps réel", "Productivité", "Heures travaillées", "Coût MO", "Sous-traitants", "Répartition métiers", "Pointage RFID"]),
    sections: [
      section("Heatmap présence", "Présence par chantier et plage horaire", "mart.real_estate_presence_heatmap", "heatmap", ["Site", "Métier", "Heure", "Badge RFID"]),
      section("Productivité chantier", "Productivité et temps travaillé", "mart.real_estate_site_productivity", "line", ["Productivité", "Heures", "Coût MO"]),
    ],
  },
  security: {
    key: "security",
    title: "Sécurité",
    subtitle: "Connexion K-Shield : accès sites, incidents, accidents, EPI, alarmes et zones interdites.",
    status: MART_STATUS,
    accent: "#D92B55",
    icon: <Shield {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_security_kpi",
    home: true,
    kpis: metricKpis("mart.real_estate_security_kpi", ["Accès sites", "Présence", "Incidents", "Accidents", "EPI", "Alarmes", "Zones interdites", "Alertes RFID"]),
    sections: [
      section("Incidents sécurité", "Incidents, accidents et alarmes", "mart.real_estate_security_incidents", "bar", ["Incidents", "Accidents", "Alarmes", "EPI"]),
      section("Zones & RFID", "Accès et zones interdites", "mart.real_estate_security_access", "heatmap", ["Site", "Zone", "Badge RFID", "Alerte"]),
    ],
  },
  clients: {
    key: "clients",
    title: "Relation Client",
    subtitle: "Connexion CRM : clients, prospects, réclamations, paiements, satisfaction, tickets et SAV.",
    status: MART_STATUS,
    accent: "#7A5AF8",
    icon: <Network {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_customer_kpi",
    home: true,
    kpis: metricKpis("mart.real_estate_customer_kpi", ["Clients", "Prospects", "Réclamations", "Paiements", "Satisfaction", "Tickets", "Demandes SAV"]),
    sections: [
      section("Satisfaction & SAV", "Tickets, réclamations et demandes SAV", "mart.real_estate_customer_service", "line", ["Tickets", "Réclamations", "SAV", "Satisfaction"]),
      section("Paiements clients", "Paiements, retards et recouvrements", "mart.real_estate_customer_payments", "bar", ["Paiements", "Retards", "Recouvrements"]),
    ],
  },
  patrimoine: {
    key: "patrimoine",
    title: "Patrimoine",
    subtitle: "Valeur totale, bâtiments, terrains, équipements, évolution valeur et amortissements.",
    status: MART_STATUS,
    accent: "#416FF4",
    icon: <Building {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_asset_value_kpi",
    home: true,
    kpis: metricKpis("mart.real_estate_asset_value_kpi", ["Valeur totale patrimoine", "Valeur bâtiments", "Valeur terrains", "Valeur équipements", "Evolution valeur", "Amortissements"]),
    sections: [
      section("Evolution valeur", "Valeur patrimoniale et amortissements", "mart.real_estate_asset_value_evolution", "line", ["Bâtiments", "Terrains", "Equipements", "Amortissements"]),
      section("Composition patrimoine", "Répartition par classe d'actif", "mart.real_estate_asset_composition", "pie", ["Bâtiments", "Terrains", "Equipements"]),
    ],
  },
  risques: {
    key: "risques",
    title: "Gouvernance des Risques",
    subtitle: "Retards, dépassements, cash négatif, stocks critiques, incidents, juridique et alertes.",
    status: MART_STATUS,
    accent: "#D92B55",
    icon: <ChartPie {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_risk_kpi",
    home: true,
    kpis: metricKpis("mart.real_estate_risk_kpi", ["Retards", "Dépassements budget", "Retards paiement", "Retards livraison", "Stocks critiques", "Incidents sécurité", "Cash négatif", "Contrats expirants", "Alertes juridiques"]),
    rows: [
      { title: "Critique", detail: "Risque rouge — donnée issue de mart.real_estate_risk_kpi", accent: "#D92B55" },
      { title: "Important", detail: "Risque orange — donnée issue de mart.real_estate_risk_kpi", accent: "#FF8735" },
      { title: "Moyen", detail: "Risque jaune — donnée issue de mart.real_estate_risk_kpi", accent: "#E8B923" },
      { title: "Normal", detail: "Risque vert — donnée issue de mart.real_estate_risk_kpi", accent: "#42BFA0" },
    ],
    sections: [
      section("Matrice risques", "Criticité par programme et domaine", "mart.real_estate_risk_matrix", "heatmap", ["Programme", "Budget", "Planning", "Cash", "Sécurité"]),
      section("Evolution risques", "Ouvertures et résolutions", "mart.real_estate_risk_evolution", "line", ["Ouverts", "Résolus", "Critiques"]),
    ],
  },
  ai: {
    key: "ai",
    title: "Centre IA",
    subtitle: "Analyse décisionnelle ancrée sur le Data Warehouse : recommandations, simulations, scénarios et prévisions.",
    status: "IA ancrée EDW — aucune donnée inventée",
    accent: "#060606",
    icon: <CheckCircle {...ICON_SIZE} />,
    kind: "ai",
    source: "analytics.real_estate_ai_insights",
    home: true,
    kpis: metricKpis("analytics.real_estate_ai_insights", ["Rentabilité", "Retards", "Ventes", "Trésorerie", "Cash Flow", "Qualité", "Productivité", "Performance commerciale", "Performance RH", "Performance financière"]),
    rows: [
      { title: "Pourquoi les ventes diminuent ?", detail: "Réponse autorisée uniquement si mart.real_estate_sales_kpi est disponible", accent: "#416FF4" },
      { title: "Pourquoi le budget explose ?", detail: "Analyse basée sur mart.real_estate_budget_evolution", accent: "#D92B55" },
      { title: "Quelle sera la trésorerie dans 90 jours ?", detail: "Prévision basée sur analytics.real_estate_cash_forecast", accent: "#42BFA0" },
      { title: "Quels projets doivent être accélérés ?", detail: "Scénario basé sur planning, ventes, cash et risques", accent: "#FF8735" },
    ],
    sections: [
      section("Prévisions IA", "Cash, ventes et retards projetés", "analytics.real_estate_forecasts", "line", ["Cash 90j", "Ventes", "Retards"]),
      section("Priorités IA", "Recommandations classées par impact", "analytics.real_estate_recommendations", "radar", ["Impact", "Urgence", "Cash", "Risque", "ROI"]),
    ],
  },
  alerts: {
    key: "alerts",
    title: "Centre d'Alertes",
    subtitle: "Alertes intelligentes : chantiers, budget, cash, contrats, stock, paiements et ventes.",
    status: MART_STATUS,
    accent: "#FF8735",
    icon: <Bell {...ICON_SIZE} />,
    kind: "notifications",
    source: "mart.real_estate_alerts",
    home: true,
    rows: [
      { title: "Chantier arrêté", detail: "Règle critique — mart.real_estate_alerts", accent: "#D92B55" },
      { title: "Dépassement budget", detail: "Règle critique — mart.real_estate_alerts", accent: "#D92B55" },
      { title: "Cash négatif", detail: "Règle critique — mart.real_estate_alerts", accent: "#D92B55" },
      { title: "Contrat arrivant à échéance", detail: "Règle critique — mart.real_estate_alerts", accent: "#D92B55" },
      { title: "Retard supérieur à 30 jours", detail: "Règle importante — mart.real_estate_alerts", accent: "#FF8735" },
      { title: "Stock critique", detail: "Règle importante — mart.real_estate_alerts", accent: "#FF8735" },
      { title: "Paiement client en retard", detail: "Règle importante — mart.real_estate_alerts", accent: "#FF8735" },
      { title: "Nouvelle vente", detail: "Signal positif — mart.real_estate_alerts", accent: "#42BFA0" },
      { title: "Nouveau programme", detail: "Signal positif — mart.real_estate_alerts", accent: "#42BFA0" },
      { title: "Livraison réalisée", detail: "Signal positif — mart.real_estate_alerts", accent: "#42BFA0" },
    ],
  },
  reports: {
    key: "reports",
    title: "Rapports",
    subtitle: "Rapports DG, investisseurs, DAF, direction technique et direction commerciale.",
    status: MART_STATUS,
    accent: "#5B6470",
    icon: <FileText {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_reporting",
    home: true,
    kpis: metricKpis("mart.real_estate_reporting", ["Rapports générés", "Exports planifiés", "Destinataires", "Validations en attente"]),
    sections: [
      section("Rapports programmés", "Fréquence, périmètre et statut", "mart.real_estate_report_schedule", "gantt", ["DG", "Investisseurs", "DAF", "Technique", "Commercial"]),
    ],
  },
  "hr-executive": {
    key: "hr-executive",
    title: "Executive HR Overview",
    subtitle: "Vue DG et DRH Groupe : effectifs, turnover, présence, masse salariale, performance et mobilités.",
    status: MART_STATUS,
    accent: "#416FF4",
    icon: <Users {...ICON_SIZE} />,
    kind: "default",
    source: "mart.hr_executive_kpi",
    home: true,
    kpis: metricKpis("mart.hr_executive_kpi", [
      "Nombre total d'employés",
      "Employés actifs",
      "Employés inactifs",
      "Effectif siège",
      "Effectif filiales",
      "Effectif par pays",
      "Effectif par région",
      "Effectif par département",
      "Effectif par métier",
      "Effectif par contrat",
      "Turnover",
      "Taux de présence",
      "Absentéisme",
      "Productivité",
      "Satisfaction",
      "Performance moyenne",
      "Coût RH",
      "Masse salariale",
      "Recrutements",
      "Départs",
      "Promotions",
      "Mobilités internes",
    ]),
    sections: [
      section("Evolution effectif", "Variation mensuelle des employés actifs, inactifs et filiales", "mart.hr_headcount_monthly", "line", ["Actifs", "Inactifs", "Siège", "Filiales"]),
      section("Evolution turnover", "Entrées, départs et taux de rotation", "mart.hr_turnover_monthly", "line", ["Entrées", "Départs", "Turnover"]),
      section("Evolution masse salariale", "Masse salariale, coût RH et charges sociales", "mart.hr_payroll_monthly", "bar", ["Masse salariale", "Charges", "Coût RH"]),
      section("Evolution absentéisme", "Absences, retards et présence consolidée", "mart.hr_absenteeism_monthly", "line", ["Absences", "Retards", "Présence"]),
      section("Evolution recrutements", "Recrutements, promotions et mobilités internes", "mart.hr_recruitment_monthly", "bar", ["Recrutements", "Promotions", "Mobilités"]),
    ],
  },
  "hr-workforce": {
    key: "hr-workforce",
    title: "Workforce Analytics",
    subtitle: "Employés, contractuels, consultants, prestataires, stagiaires, freelances et répartition du capital humain.",
    status: MART_STATUS,
    accent: "#42BFA0",
    icon: <Users {...ICON_SIZE} />,
    kind: "default",
    source: "mart.hr_workforce_kpi",
    home: true,
    kpis: metricKpis("mart.hr_workforce_kpi", [
      "Effectif",
      "Employés",
      "Contractuels",
      "Consultants",
      "Prestataires",
      "Stagiaires",
      "Freelances",
      "Ratio managers",
      "Ratio hommes/femmes",
      "Ratio CDI/CDD",
      "Âge moyen",
      "Ancienneté moyenne",
    ]),
    sections: [
      section("Pyramide des âges", "Répartition par sexe, tranche d'âge et ancienneté", "mart.hr_age_pyramid", "bar", ["18-25", "26-35", "36-45", "46-55", "56+"]),
      section("Répartition métiers", "Filiale, département, direction et métier", "mart.hr_job_distribution", "pie", ["Direction", "Commercial", "Technique", "Finance", "Support"]),
      section("Répartition hiérarchique", "Niveaux hiérarchiques et span of control", "mart.hr_hierarchy_distribution", "radar", ["CODIR", "Managers", "Experts", "Opérationnels", "Support"]),
      section("Cartographie effectifs", "Pays, région, filiale, site et département", "mart.hr_workforce_map", "heatmap", ["Pays", "Région", "Filiale", "Site", "Département"]),
    ],
  },
  "hr-organization": {
    key: "hr-organization",
    title: "Organization",
    subtitle: "Organigrammes groupe, filiale et département, managers, span of control, succession et postes vacants.",
    status: MART_STATUS,
    accent: "#8A63D2",
    icon: <Network {...ICON_SIZE} />,
    kind: "default",
    source: "mart.hr_organization_kpi",
    home: true,
    kpis: metricKpis("mart.hr_organization_kpi", ["Organigramme Groupe", "Organigramme Filiale", "Organigramme Département", "Nombre de managers", "Span of control", "Hiérarchie", "Succession", "Vacances de postes"]),
    sections: [
      section("Organigramme dynamique", "Structure groupe, filiales et départements", "mart.hr_org_chart", "gantt", ["Groupe", "Filiale", "Département", "Equipe"]),
      section("Succession & postes vacants", "Plans de succession, criticité et vacance de poste", "mart.hr_succession_vacancy", "bar", ["Succession", "Vacances", "Managers", "Criticité"]),
    ],
  },
  "hr-attendance": {
    key: "hr-attendance",
    title: "Attendance & Presence",
    subtitle: "Connexion Odoo RH et K-Shield RFID : présents, absents, retards, pointages et heures travaillées.",
    status: MART_STATUS,
    accent: "#FF8735",
    icon: <CheckCircle {...ICON_SIZE} />,
    kind: "default",
    source: "mart.hr_attendance_kpi",
    home: true,
    kpis: metricKpis("mart.hr_attendance_kpi", ["Présents", "Absents", "Retards", "Pointages", "Sorties", "Entrées", "Heures travaillées", "Heures supplémentaires", "Présence par chantier", "Présence siège", "Présence filiales"]),
    sections: [
      section("Heatmap présence", "Présence par site, filiale, chantier et plage horaire", "mart.hr_presence_heatmap", "heatmap", ["Siège", "Filiales", "Chantiers", "Sites"]),
      section("Evolution journalière", "Présence temps réel, entrées, sorties et heures travaillées", "mart.hr_attendance_daily", "line", ["Présents", "Entrées", "Sorties", "Heures"]),
      section("Top retards & absences", "Retards répétés, absences et anomalies RFID", "mart.hr_attendance_exceptions", "bar", ["Retards", "Absences", "Anomalies"]),
    ],
  },
  "hr-leave": {
    key: "hr-leave",
    title: "Leave Management",
    subtitle: "Congés, permissions, maladies, maternité, congés annuels, exceptionnels et non payés.",
    status: MART_STATUS,
    accent: "#2D74E0",
    icon: <Calendar {...ICON_SIZE} />,
    kind: "default",
    source: "mart.hr_leave_kpi",
    home: true,
    kpis: metricKpis("mart.hr_leave_kpi", ["Congés demandés", "Congés validés", "Congés refusés", "Solde congés", "Congés restants", "Permissions", "Maladies", "Congés maternité", "Congés annuels", "Congés exceptionnels", "Congés non payés"]),
    sections: [
      section("Flux congés", "Demandes, validations, refus et soldes par période", "mart.hr_leave_flow", "bar", ["Demandés", "Validés", "Refusés", "Restants"]),
      section("Typologie congés", "Maladie, annuel, maternité, exceptionnel et non payé", "mart.hr_leave_mix", "pie", ["Maladie", "Annuel", "Maternité", "Exceptionnel", "Non payé"]),
    ],
  },
  "hr-recruitment": {
    key: "hr-recruitment",
    title: "Recruitment Analytics",
    subtitle: "Offres, candidatures, entretiens, recrutements, pipeline, coûts, sources et conversion.",
    status: MART_STATUS,
    accent: "#7A5AF8",
    icon: <Briefcase {...ICON_SIZE} />,
    kind: "default",
    source: "mart.hr_recruitment_kpi",
    home: true,
    kpis: metricKpis("mart.hr_recruitment_kpi", ["Offres", "Candidatures", "Entretiens", "Recrutements", "Pipeline", "Temps moyen recrutement", "Coût recrutement", "Source candidats", "Conversion"]),
    sections: [
      section("Pipeline RH", "Offres vers recrutements signés", "mart.hr_recruitment_pipeline", "funnel", ["Offres", "Candidatures", "Entretiens", "Shortlist", "Recrutements"]),
      section("Délais recrutement", "Temps moyen par étape et par poste", "mart.hr_recruitment_cycle_time", "gantt", ["Sourcing", "Entretien", "Validation", "Contrat", "Onboarding"]),
      section("Source candidats", "Sources, conversion et coût d'acquisition", "mart.hr_candidate_sources", "pie", ["Cooptation", "LinkedIn", "Cabinet", "Site carrière", "Autres"]),
    ],
  },
  "hr-payroll": {
    key: "hr-payroll",
    title: "Payroll Analytics",
    subtitle: "Connexion Odoo Comptabilité : masse salariale, charges, primes, bonus, indemnités et coûts RH.",
    status: MART_STATUS,
    accent: "#42BFA0",
    icon: <Wallet {...ICON_SIZE} />,
    kind: "default",
    source: "mart.hr_payroll_kpi",
    home: true,
    kpis: metricKpis("mart.hr_payroll_kpi", ["Masse salariale", "Charges sociales", "Primes", "Bonus", "Indemnités", "Heures supplémentaires", "Coût employé", "Coût département", "Coût filiale", "Coût siège"]),
    sections: [
      section("Evolution masse salariale", "Masse salariale mensuelle et charges associées", "mart.hr_payroll_evolution", "line", ["Masse salariale", "Charges", "Primes"]),
      section("Répartition coûts RH", "Coût par filiale, département et siège", "mart.hr_cost_distribution", "pie", ["Siège", "Filiales", "Départements", "Sites"]),
      section("Projection annuelle", "Projection masse salariale et coût employé", "analytics.hr_payroll_forecast", "line", ["Prévision 3 mois", "Prévision 6 mois", "Prévision 12 mois"]),
    ],
  },
  "hr-performance": {
    key: "hr-performance",
    title: "Performance Management",
    subtitle: "Objectifs, évaluations, scores, top performers, talents à risque et performance des équipes.",
    status: MART_STATUS,
    accent: "#416FF4",
    icon: <Target {...ICON_SIZE} />,
    kind: "default",
    source: "mart.hr_performance_kpi",
    home: true,
    kpis: metricKpis("mart.hr_performance_kpi", ["Objectifs", "Evaluations", "Scores", "Top Performers", "Low Performers", "Objectifs atteints", "Objectifs en retard", "Notation managers", "Score moyen", "Employés à haut potentiel", "Employés à risque", "Performance équipe", "Performance département"]),
    sections: [
      section("Distribution scores", "Répartition des scores d'évaluation", "mart.hr_performance_distribution", "bar", ["A", "B", "C", "D", "Risque"]),
      section("Radar compétences", "Compétences, objectifs et comportement", "mart.hr_performance_radar", "radar", ["Objectifs", "Compétences", "Leadership", "Collaboration", "Impact"]),
      section("Classement performance", "Top performers, low performers et équipes", "mart.hr_performance_ranking", "bar", ["Top", "Moyen", "Risque", "Equipe"]),
    ],
  },
  "hr-training": {
    key: "hr-training",
    title: "Training Analytics",
    subtitle: "Formations, certifications, compétences, budget, participation et heures de formation.",
    status: MART_STATUS,
    accent: "#E08A1E",
    icon: <FileText {...ICON_SIZE} />,
    kind: "default",
    source: "mart.hr_training_kpi",
    home: true,
    kpis: metricKpis("mart.hr_training_kpi", ["Formations", "Certifications", "Compétences", "Budget", "Participation", "Heures formation", "Budget consommé", "Budget restant", "Taux participation", "Certification obtenue", "Compétences critiques", "Compétences manquantes"]),
    sections: [
      section("Participation formation", "Participation, heures et certifications obtenues", "mart.hr_training_participation", "bar", ["Participants", "Heures", "Certifications"]),
      section("Budget formation", "Budget consommé, restant et compétences critiques", "mart.hr_training_budget", "line", ["Consommé", "Restant", "Critique"]),
    ],
  },
  "hr-skills": {
    key: "hr-skills",
    title: "Skills Analytics",
    subtitle: "Compétences disponibles, critiques, rares, futures, gaps et cartographie des compétences.",
    status: MART_STATUS,
    accent: "#8A63D2",
    icon: <Grid {...ICON_SIZE} />,
    kind: "default",
    source: "mart.hr_skills_kpi",
    home: true,
    kpis: metricKpis("mart.hr_skills_kpi", ["Compétences disponibles", "Compétences critiques", "Compétences rares", "Compétences futures", "Gap de compétences", "Cartographie des compétences", "Matrix Skills", "Radar Skills"]),
    sections: [
      section("Matrix Skills", "Matrice compétences par métier, département et niveau", "mart.hr_skills_matrix", "heatmap", ["Métier", "Département", "Niveau", "Criticité"]),
      section("Radar Skills", "Compétences actuelles, futures et gaps", "mart.hr_skills_radar", "radar", ["Actuelles", "Critiques", "Rares", "Futures", "Gap"]),
    ],
  },
  "hr-career": {
    key: "hr-career",
    title: "Career Management",
    subtitle: "Promotions, mobilités, succession, talents, plans carrière, high potentials et risk employees.",
    status: MART_STATUS,
    accent: "#2BB7A3",
    icon: <CheckCircle {...ICON_SIZE} />,
    kind: "default",
    source: "mart.hr_career_kpi",
    home: true,
    kpis: metricKpis("mart.hr_career_kpi", ["Promotions", "Mobilités", "Succession", "Talents", "Plans carrière", "High Potentials", "Risk Employees"]),
    sections: [
      section("Mobilité & promotions", "Promotions, mobilité interne et plans carrière", "mart.hr_career_mobility", "line", ["Promotions", "Mobilités", "Plans"]),
      section("Talents & succession", "High potentials, risk employees et succession", "mart.hr_talent_succession", "radar", ["Potentiel", "Risque", "Succession", "Performance", "Rétention"]),
    ],
  },
  "hr-experience": {
    key: "hr-experience",
    title: "Employee Experience",
    subtitle: "Satisfaction, engagement, eNPS, réclamations, suggestions, feedback, reconnaissance et climat social.",
    status: MART_STATUS,
    accent: "#D92B55",
    icon: <User {...ICON_SIZE} />,
    kind: "default",
    source: "mart.hr_employee_experience_kpi",
    home: true,
    kpis: metricKpis("mart.hr_employee_experience_kpi", ["Satisfaction", "Engagement", "eNPS", "Réclamations", "Suggestions", "Feedback", "Reconnaissance", "Climat social"]),
    sections: [
      section("Evolution satisfaction", "Satisfaction, engagement et eNPS", "mart.hr_experience_satisfaction", "line", ["Satisfaction", "Engagement", "eNPS"]),
      section("Climat social", "Réclamations, suggestions et feedback", "mart.hr_social_climate", "heatmap", ["Réclamations", "Suggestions", "Feedback", "Reconnaissance"]),
    ],
  },
  "hr-health-safety": {
    key: "hr-health-safety",
    title: "Health & Safety",
    subtitle: "Connexion K-Shield : accidents, incidents, EPI, médecine du travail, visites médicales et alertes.",
    status: MART_STATUS,
    accent: "#D92B55",
    icon: <Shield {...ICON_SIZE} />,
    kind: "default",
    source: "mart.hr_health_safety_kpi",
    home: true,
    kpis: metricKpis("mart.hr_health_safety_kpi", ["Accidents", "Incidents", "EPI", "Médecine du travail", "Visites médicales", "Formations sécurité", "Conformité", "Alertes"]),
    sections: [
      section("Incidents HSE", "Accidents, incidents, alertes et EPI", "mart.hr_hse_incidents", "bar", ["Accidents", "Incidents", "EPI", "Alertes"]),
      section("Conformité santé", "Visites médicales, formations sécurité et médecine du travail", "mart.hr_hse_compliance", "gantt", ["Visites", "Formations", "Habilitations", "Alertes"]),
    ],
  },
  "hr-compliance": {
    key: "hr-compliance",
    title: "Compliance",
    subtitle: "Contrats expirants, documents manquants, visites médicales, certifications, habilitations, audits et RGPD.",
    status: MART_STATUS,
    accent: "#5B6470",
    icon: <Receipt {...ICON_SIZE} />,
    kind: "default",
    source: "mart.hr_compliance_kpi",
    home: true,
    kpis: metricKpis("mart.hr_compliance_kpi", ["Contrats expirants", "Documents manquants", "Visites médicales expirées", "Certifications expirées", "Habilitations", "Audits RH", "Conformité réglementaire", "RGPD"]),
    sections: [
      section("Echéances conformité", "Contrats, visites, certifications et habilitations", "mart.hr_compliance_deadlines", "gantt", ["Contrats", "Visites", "Certifications", "Habilitations"]),
      section("Audits RH", "Conformité réglementaire, RGPD et documents manquants", "mart.hr_compliance_audits", "bar", ["Documents", "Audits", "RGPD", "Réglementaire"]),
    ],
  },
  "hr-planning": {
    key: "hr-planning",
    title: "Workforce Planning",
    subtitle: "Prévisions effectifs, départs, recrutements, masse salariale, compétences, retraite et budget RH.",
    status: MART_STATUS,
    accent: "#416FF4",
    icon: <ChartPie {...ICON_SIZE} />,
    kind: "default",
    source: "analytics.hr_workforce_planning",
    home: true,
    kpis: metricKpis("analytics.hr_workforce_planning", ["Prévisions effectifs", "Prévisions départs", "Prévisions recrutements", "Prévisions masse salariale", "Prévisions compétences", "Prévisions retraite", "Simulation budget RH"]),
    sections: [
      section("Prévisions effectifs", "Effectifs, départs, recrutements et retraites", "analytics.hr_headcount_forecast", "line", ["Effectifs", "Départs", "Recrutements", "Retraite"]),
      section("Simulation budget RH", "Masse salariale, compétences et scénarios", "analytics.hr_budget_simulation", "line", ["Budget", "Masse salariale", "Compétences"]),
    ],
  },
  "hr-diversity": {
    key: "hr-diversity",
    title: "Diversity & Inclusion",
    subtitle: "Parité, âges, nationalités, diversité métiers et évolution D&I.",
    status: MART_STATUS,
    accent: "#7A5AF8",
    icon: <Layers {...ICON_SIZE} />,
    kind: "default",
    source: "mart.hr_diversity_kpi",
    home: true,
    kpis: metricKpis("mart.hr_diversity_kpi", ["Parité", "Âges", "Nationalités", "Diversité métiers", "Evolution D&I"]),
    sections: [
      section("Parité & âges", "Répartition par genre, âge et ancienneté", "mart.hr_diversity_demographics", "bar", ["Parité", "Âges", "Ancienneté"]),
      section("Diversité métiers", "Nationalités, métiers et évolution D&I", "mart.hr_diversity_jobs", "pie", ["Nationalités", "Métiers", "Directions", "Sites"]),
    ],
  },
  "hr-ai": {
    key: "hr-ai",
    title: "AI HR Insights",
    subtitle: "Centre IA RH : synthèses DRH, notes CODIR, recommandations, prévisions, simulations et plans d'action.",
    status: "IA RH ancrée EDW — aucune donnée inventée",
    accent: "#060606",
    icon: <CheckCircle {...ICON_SIZE} />,
    kind: "ai",
    source: "analytics.hr_ai_insights",
    home: true,
    kpis: metricKpis("analytics.hr_ai_insights", ["Turnover", "Productivité", "Présence", "Congés", "Performance", "Satisfaction", "Compétences", "Recrutement", "Masse salariale"]),
    rows: [
      { title: "Pourquoi le turnover augmente ?", detail: "Réponse autorisée uniquement si mart.hr_turnover_monthly est disponible", accent: "#D92B55" },
      { title: "Quels départements sont sous-effectifs ?", detail: "Analyse basée sur mart.hr_workforce_kpi et analytics.hr_workforce_planning", accent: "#416FF4" },
      { title: "Quelle sera la masse salariale dans 12 mois ?", detail: "Prévision basée sur analytics.hr_payroll_forecast", accent: "#42BFA0" },
      { title: "Quelles compétences seront nécessaires dans les 3 prochaines années ?", detail: "Scénario basé sur analytics.hr_skills_forecast", accent: "#8A63D2" },
    ],
    sections: [
      section("Prévisions IA RH", "Turnover, présence, recrutement, compétences et masse salariale", "analytics.hr_forecasts", "line", ["Turnover", "Présence", "Recrutement", "Masse salariale"]),
      section("Priorités DRH", "Recommandations classées par risque, urgence et impact", "analytics.hr_recommendations", "radar", ["Risque", "Urgence", "Impact", "Coût", "Talent"]),
    ],
  },
  "hr-alerts": {
    key: "hr-alerts",
    title: "Centre d'Alertes RH",
    subtitle: "Alertes RH avec criticité : turnover, contrats, effectifs, accidents, paie, congés et conformité.",
    status: MART_STATUS,
    accent: "#FF8735",
    icon: <Bell {...ICON_SIZE} />,
    kind: "notifications",
    source: "mart.hr_alerts",
    home: true,
    rows: [
      { title: "Turnover supérieur au seuil", detail: "Critique — mart.hr_alerts", accent: "#D92B55" },
      { title: "Employé clé en risque de départ", detail: "Critique — mart.hr_alerts", accent: "#D92B55" },
      { title: "Contrat arrivant à échéance", detail: "Critique — mart.hr_alerts", accent: "#D92B55" },
      { title: "Effectif critique sur un chantier", detail: "Critique — mart.hr_alerts", accent: "#D92B55" },
      { title: "Accident grave", detail: "Critique — mart.hr_alerts", accent: "#D92B55" },
      { title: "Masse salariale dépassant le budget", detail: "Critique — mart.hr_alerts", accent: "#D92B55" },
      { title: "Congés en attente de validation", detail: "Important — mart.hr_alerts", accent: "#FF8735" },
      { title: "Absentéisme élevé", detail: "Important — mart.hr_alerts", accent: "#FF8735" },
      { title: "Formation obligatoire non suivie", detail: "Important — mart.hr_alerts", accent: "#FF8735" },
      { title: "Nouveau recrutement", detail: "Information — mart.hr_alerts", accent: "#42BFA0" },
      { title: "Promotion", detail: "Information — mart.hr_alerts", accent: "#42BFA0" },
      { title: "Nouvelle certification", detail: "Information — mart.hr_alerts", accent: "#42BFA0" },
    ],
  },
  "hr-reports": {
    key: "hr-reports",
    title: "HR Reports",
    subtitle: "Exports DRH, CODIR, filiales, départements, conformité, paie et capital humain.",
    status: MART_STATUS,
    accent: "#5B6470",
    icon: <FileText {...ICON_SIZE} />,
    kind: "default",
    source: "mart.hr_reporting",
    home: true,
    kpis: metricKpis("mart.hr_reporting", ["Rapports générés", "Exports PDF", "Exports Excel", "Exports PowerPoint", "Validations en attente", "Destinataires"]),
    sections: [
      section("Rapports RH programmés", "DRH, CODIR, filiales, départements, conformité et paie", "mart.hr_report_schedule", "gantt", ["DRH", "CODIR", "Filiales", "Départements", "Conformité", "Paie"]),
    ],
  },
  "finance-executive": {
    key: "finance-executive",
    title: "Executive Finance Overview",
    subtitle: "Vue DAF et DG : trésorerie, budget, résultat, rentabilité, risques et prévisions financières.",
    status: MART_STATUS,
    accent: "#42BFA0",
    icon: <Wallet {...ICON_SIZE} />,
    kind: "default",
    source: "mart.finance_executive_kpi",
    home: true,
    kpis: metricKpis("mart.finance_executive_kpi", ["Chiffre d'affaires", "Résultat net", "EBITDA", "Cash disponible", "Budget consommé", "Marge", "Créances", "Dettes", "Trésorerie nette", "Risque financier"]),
    sections: [
      section("Evolution résultat", "CA, marge, EBITDA et résultat net", "mart.finance_result_monthly", "line", ["CA", "Marge", "EBITDA", "Résultat"]),
      section("Evolution cash", "Encaissements, décaissements et trésorerie nette", "mart.finance_cash_monthly", "line", ["Encaissements", "Décaissements", "Cash net"]),
      section("Budget vs réalisé", "Budget consommé, restant et écarts", "mart.finance_budget_variance", "bar", ["Budget", "Réalisé", "Ecart"]),
    ],
  },
  "finance-treasury": {
    key: "finance-treasury",
    title: "Trésorerie",
    subtitle: "Cash disponible, banques, engagements, flux entrants/sortants et projection de liquidité.",
    status: MART_STATUS,
    accent: "#2D74E0",
    icon: <DollarCircle {...ICON_SIZE} />,
    kind: "default",
    source: "mart.finance_treasury_kpi",
    home: true,
    kpis: metricKpis("mart.finance_treasury_kpi", ["Cash disponible", "Banques", "Engagements", "Cash engagé", "Cash net", "Projection liquidité"]),
    sections: [
      section("Cash position", "Solde bancaire et cash engagé", "mart.finance_cash_position", "line", ["Banques", "Engagé", "Net"]),
      section("Projection liquidité", "Prévision de trésorerie court terme", "analytics.finance_liquidity_forecast", "line", ["J+30", "J+60", "J+90"]),
    ],
  },
  "finance-cash-in": {
    key: "finance-cash-in",
    title: "Encaissements",
    subtitle: "Encaissements clients, ventes, loyers, recouvrements et flux entrants par filiale.",
    status: MART_STATUS,
    accent: "#42BFA0",
    icon: <Receipt {...ICON_SIZE} />,
    kind: "default",
    source: "mart.finance_cash_in_kpi",
    home: true,
    kpis: metricKpis("mart.finance_cash_in_kpi", ["Encaissements", "Clients", "Ventes", "Loyers", "Recouvrements", "Flux entrants"]),
    sections: [section("Flux entrants", "Encaissements par source et période", "mart.finance_cash_in_flow", "bar", ["Clients", "Ventes", "Loyers", "Recouvrement"])],
  },
  "finance-cash-out": {
    key: "finance-cash-out",
    title: "Décaissements",
    subtitle: "Paiements fournisseurs, charges, salaires, taxes et flux sortants par centre de coût.",
    status: MART_STATUS,
    accent: "#D92B55",
    icon: <Receipt {...ICON_SIZE} />,
    kind: "default",
    source: "mart.finance_cash_out_kpi",
    home: true,
    kpis: metricKpis("mart.finance_cash_out_kpi", ["Décaissements", "Fournisseurs", "Charges", "Salaires", "Taxes", "Flux sortants"]),
    sections: [section("Flux sortants", "Décaissements par nature et période", "mart.finance_cash_out_flow", "bar", ["Fournisseurs", "Charges", "Salaires", "Taxes"])],
  },
  "finance-budget": {
    key: "finance-budget",
    title: "Budget",
    subtitle: "Budget initial, révisé, consommé, restant, écarts et alertes de dépassement.",
    status: MART_STATUS,
    accent: "#FF8735",
    icon: <Calculator {...ICON_SIZE} />,
    kind: "default",
    source: "mart.finance_budget_kpi",
    home: true,
    kpis: metricKpis("mart.finance_budget_kpi", ["Budget initial", "Budget révisé", "Budget consommé", "Budget restant", "Ecart", "Dépassements"]),
    sections: [section("Budget vs réalisé", "Suivi budgétaire et écarts", "mart.finance_budget_tracking", "line", ["Initial", "Révisé", "Réalisé", "Ecart"])],
  },
  "finance-accounting": {
    key: "finance-accounting",
    title: "Comptabilité",
    subtitle: "Synthèse comptable : balance, grand livre, journaux, factures, créances et dettes.",
    status: MART_STATUS,
    accent: "#5B6470",
    icon: <Calculator {...ICON_SIZE} />,
    kind: "default",
    source: "mart.finance_accounting_kpi",
    home: true,
    kpis: metricKpis("mart.finance_accounting_kpi", ["Balance", "Grand Livre", "Journaux", "Factures", "Créances", "Dettes", "TVA", "Echéances"]),
    sections: [section("Synthèse comptable", "Agrégats comptables par période", "mart.finance_accounting_summary", "bar", ["Balance", "Journaux", "Factures", "TVA"])],
  },
  "finance-balance": {
    key: "finance-balance",
    title: "Balance",
    subtitle: "Balance générale, auxiliaire, soldes débiteurs/créditeurs et comptes sensibles.",
    status: MART_STATUS,
    accent: "#416FF4",
    icon: <FileText {...ICON_SIZE} />,
    kind: "default",
    source: "mart.finance_balance_kpi",
    home: true,
    kpis: metricKpis("mart.finance_balance_kpi", ["Soldes débiteurs", "Soldes créditeurs", "Comptes actifs", "Comptes sensibles"]),
    sections: [section("Balance comptable", "Soldes par classe et compte", "mart.finance_balance", "bar", ["Classe 1", "Classe 2", "Classe 4", "Classe 7"])],
  },
  "finance-ledger": {
    key: "finance-ledger",
    title: "Grand Livre",
    subtitle: "Grand livre, écritures, lettrage, comptes mouvementés et anomalies comptables.",
    status: MART_STATUS,
    accent: "#8A63D2",
    icon: <FileText {...ICON_SIZE} />,
    kind: "default",
    source: "mart.finance_ledger_kpi",
    home: true,
    kpis: metricKpis("mart.finance_ledger_kpi", ["Ecritures", "Comptes mouvementés", "Lettrage", "Anomalies"]),
    sections: [section("Mouvements comptables", "Ecritures par compte et période", "mart.finance_ledger_entries", "line", ["Débit", "Crédit", "Solde"])],
  },
  "finance-invoices": {
    key: "finance-invoices",
    title: "Factures",
    subtitle: "Factures clients/fournisseurs, statuts, échéances, retards et litiges.",
    status: MART_STATUS,
    accent: "#E08A1E",
    icon: <Receipt {...ICON_SIZE} />,
    kind: "default",
    source: "mart.finance_invoice_kpi",
    home: true,
    kpis: metricKpis("mart.finance_invoice_kpi", ["Factures émises", "Factures reçues", "Factures échues", "Retards", "Litiges"]),
    sections: [section("Facturation", "Volume et statut des factures", "mart.finance_invoices", "bar", ["Emises", "Reçues", "Echues", "Litiges"])],
  },
  "finance-receivables": {
    key: "finance-receivables",
    title: "Créances",
    subtitle: "Créances clients, aging, retards paiement, provisions et exposition.",
    status: MART_STATUS,
    accent: "#42BFA0",
    icon: <DollarCircle {...ICON_SIZE} />,
    kind: "default",
    source: "mart.finance_receivables_kpi",
    home: true,
    kpis: metricKpis("mart.finance_receivables_kpi", ["Créances", "Aging 30j", "Aging 60j", "Aging 90j", "Provisions", "Exposition"]),
    sections: [section("Aging créances", "Ancienneté des créances clients", "mart.finance_receivables_aging", "bar", ["0-30j", "31-60j", "61-90j", "+90j"])],
  },
  "finance-payables": {
    key: "finance-payables",
    title: "Dettes",
    subtitle: "Dettes fournisseurs, échéances, engagements, dettes fiscales et sociales.",
    status: MART_STATUS,
    accent: "#D92B55",
    icon: <DollarCircle {...ICON_SIZE} />,
    kind: "default",
    source: "mart.finance_payables_kpi",
    home: true,
    kpis: metricKpis("mart.finance_payables_kpi", ["Dettes fournisseurs", "Echéances", "Engagements", "Fiscal", "Social", "Retards"]),
    sections: [section("Aging dettes", "Ancienneté et échéances des dettes", "mart.finance_payables_aging", "bar", ["0-30j", "31-60j", "61-90j", "+90j"])],
  },
  "finance-recovery": {
    key: "finance-recovery",
    title: "Recouvrement",
    subtitle: "Recouvrement, relances, promesses de paiement, litiges et cash attendu.",
    status: MART_STATUS,
    accent: "#2BB7A3",
    icon: <Target {...ICON_SIZE} />,
    kind: "default",
    source: "mart.finance_recovery_kpi",
    home: true,
    kpis: metricKpis("mart.finance_recovery_kpi", ["Relances", "Promesses", "Cash attendu", "Litiges", "Taux recouvrement"]),
    sections: [section("Pipeline recouvrement", "Relances vers encaissements", "mart.finance_recovery_pipeline", "funnel", ["A relancer", "Relancé", "Promesse", "Payé"])],
  },
  "finance-profitability": {
    key: "finance-profitability",
    title: "Analyse Rentabilité",
    subtitle: "Rentabilité par programme, filiale, client, produit, marge et ROI.",
    status: MART_STATUS,
    accent: "#416FF4",
    icon: <ChartPie {...ICON_SIZE} />,
    kind: "default",
    source: "mart.finance_profitability_kpi",
    home: true,
    kpis: metricKpis("mart.finance_profitability_kpi", ["Marge", "ROI", "Rentabilité filiale", "Rentabilité programme", "Rentabilité client"]),
    sections: [section("Rentabilité", "Marge et ROI par axe analytique", "mart.finance_profitability", "radar", ["Programme", "Filiale", "Client", "Produit", "ROI"])],
  },
  "finance-forecast": {
    key: "finance-forecast",
    title: "Prévisions",
    subtitle: "Prévisions trésorerie, résultat, cash-flow, budget et scénarios financiers.",
    status: MART_STATUS,
    accent: "#060606",
    icon: <CheckCircle {...ICON_SIZE} />,
    kind: "ai",
    source: "analytics.finance_forecast",
    home: true,
    kpis: metricKpis("analytics.finance_forecast", ["Prévision cash", "Prévision résultat", "Prévision budget", "Scénarios", "Anomalies"]),
    sections: [section("Prévisions financières", "Cash, résultat et budget projetés", "analytics.finance_forecast", "line", ["Cash", "Résultat", "Budget"])],
  },
  "finance-risks": {
    key: "finance-risks",
    title: "Risques Financiers",
    subtitle: "Cash négatif, dépassements, créances à risque, dettes critiques et alertes financières.",
    status: MART_STATUS,
    accent: "#D92B55",
    icon: <Shield {...ICON_SIZE} />,
    kind: "default",
    source: "mart.finance_risk_kpi",
    home: true,
    kpis: metricKpis("mart.finance_risk_kpi", ["Cash négatif", "Dépassements", "Créances à risque", "Dettes critiques", "Alertes"]),
    sections: [section("Matrice risques financiers", "Criticité des risques par axe", "mart.finance_risk_matrix", "heatmap", ["Cash", "Budget", "Créances", "Dettes"])],
  },
  "finance-reports": {
    key: "finance-reports",
    title: "Rapports Finance",
    subtitle: "Rapports DAF, DG, comptables, trésorerie, recouvrement et rentabilité.",
    status: MART_STATUS,
    accent: "#5B6470",
    icon: <FileText {...ICON_SIZE} />,
    kind: "default",
    source: "mart.finance_reporting",
    home: true,
    kpis: metricKpis("mart.finance_reporting", ["Rapports générés", "Exports", "Destinataires", "Validations"]),
    sections: [section("Rapports Finance programmés", "DAF, DG, comptabilité, trésorerie et recouvrement", "mart.finance_report_schedule", "gantt", ["DAF", "DG", "Compta", "Trésorerie", "Recouvrement"])],
  },
  groupe: {
    key: "groupe",
    title: "Vue groupe",
    subtitle: "Consolidation transverse des filiales du groupe Kaydan.",
    status: MART_STATUS,
    accent: "#8A63D2",
    icon: <Layers {...ICON_SIZE} />,
    kind: "default",
    source: "mart.group_kpi",
    kpis: metricKpis("mart.group_kpi", ["Filiales", "Effectif groupe", "CA consolidé"]),
  },
  timeline: {
    key: "timeline",
    title: "Timeline",
    subtitle: "Jalons, échéances et charge des équipes.",
    status: MART_STATUS,
    accent: "#6366F1",
    icon: <Calendar {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_timeline",
    kpis: metricKpis("mart.real_estate_timeline", ["Jalons à venir", "Tâches en retard", "Charge équipe"]),
  },
  "work-areas": {
    key: "work-areas",
    title: "Zones de travail",
    subtitle: "Sites actifs, occupation et incidents ouverts.",
    status: MART_STATUS,
    accent: "#5B8DEF",
    icon: <Grid {...ICON_SIZE} />,
    kind: "default",
    source: "mart.real_estate_work_area",
    kpis: metricKpis("mart.real_estate_work_area", ["Sites actifs", "Taux d'occupation", "Incidents ouverts"]),
  },
  notifications: {
    key: "notifications",
    title: "Notifications",
    subtitle: "Alertes data, jalons et événements du périmètre.",
    status: "Centre d'alertes",
    accent: "#FF8735",
    icon: <Bell {...ICON_SIZE} />,
    kind: "notifications",
    source: "mart.real_estate_alerts",
    rows: rows(["Mart real_estate_kpi en attente", "Mart finance_kpi en attente", "Règles d'alertes configurées"], "mart.real_estate_alerts"),
  },
  parametres: {
    key: "parametres",
    title: "Paramètres",
    subtitle: "Préférences d'affichage, périmètre et accès.",
    status: "Lecture seule",
    accent: "#5B6470",
    icon: <Cog {...ICON_SIZE} />,
    kind: "settings",
    source: "app.settings",
    rows: [
      { title: "Périmètre par défaut", detail: "Groupe (toutes filiales)", accent: "#416FF4" },
      { title: "Langue", detail: "Français", accent: "#42BFA0" },
      { title: "Thème", detail: "Clair premium", accent: "#FF8735" },
      { title: "Rôle & RBAC", detail: "Lecture seule — données gouvernées", accent: "#8A63D2" },
    ],
  },
  aide: {
    key: "aide",
    title: "Aide & Support",
    subtitle: "Documentation, catalogue de métriques et contact.",
    status: "Centre d'aide",
    accent: "#2BB7A3",
    icon: <Help {...ICON_SIZE} />,
    kind: "help",
    source: "knowledge.governance",
    rows: [
      { title: "Catalogue de métriques", detail: "Définitions et grains des KPI servis", accent: "#416FF4" },
      { title: "Gouvernance des données", detail: "RBAC, périmètre et lecture seule", accent: "#FF8735" },
      { title: "Ancrage IA", detail: "L'IA répond uniquement à partir des marts/analytics disponibles", accent: "#060606" },
    ],
  },
  profil: {
    key: "profil",
    title: "Mon profil",
    subtitle: "Compte, périmètre d'accès et préférences.",
    status: "Connecté",
    accent: "#2D74E0",
    icon: <User {...ICON_SIZE} />,
    kind: "profile",
    source: "app.profile",
    rows: [
      { title: "Rôle", detail: "Analyste pilotage groupe", accent: "#416FF4" },
      { title: "Périmètre", detail: "Groupe Kaydan — toutes filiales", accent: "#42BFA0" },
      { title: "Accès", detail: "Lecture seule (gouvernance)", accent: "#FF8735" },
    ],
  },
};

export const REAL_ESTATE_MODULE_KEYS = [
  "executive",
  "portfolio",
  "land",
  "construction",
  "vrd",
  "commercialisation",
  "rental",
  "finance",
  "treasury",
  "accounting",
  "inventory",
  "patrimoine",
  "maintenance",
  "chantier-resources",
  "security",
  "clients",
  "risques",
  "ai",
  "alerts",
  "reports",
] as const;

export const HR_MODULE_KEYS = [
  "hr-executive",
  "hr-workforce",
  "hr-organization",
  "hr-attendance",
  "hr-leave",
  "hr-recruitment",
  "hr-payroll",
  "hr-performance",
  "hr-training",
  "hr-skills",
  "hr-career",
  "hr-experience",
  "hr-health-safety",
  "hr-compliance",
  "hr-planning",
  "hr-diversity",
  "hr-ai",
  "hr-alerts",
  "hr-reports",
] as const;

export const HOME_MODULE_KEYS = [...REAL_ESTATE_MODULE_KEYS, ...HR_MODULE_KEYS];

export function getModule(key: string | undefined): ModuleDef | undefined {
  return key ? MODULES[key] : undefined;
}

export interface DashboardLink {
  key: "realEstate" | "hr" | "finance";
  title: string;
  subtitle: string;
  accent: string;
  icon: React.ReactNode;
}

export const DASHBOARD_LINKS: DashboardLink[] = [
  { key: "realEstate", title: "Real Estate", subtitle: "Cockpit de gouvernance immobilière", accent: "#FF8735", icon: <Building {...ICON_SIZE} /> },
  { key: "hr", title: "Ressources humaines", subtitle: "Cockpit de gouvernance RH", accent: "#416FF4", icon: <Users {...ICON_SIZE} /> },
  { key: "finance", title: "Finance", subtitle: "Charges, marges et trésorerie", accent: "#42BFA0", icon: <CheckCircle {...ICON_SIZE} /> },
];
