# Generated by Django 6.0.4 on 2026-06-26 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_url', models.URLField(blank=True)),
                ('auth_method', models.CharField(choices=[('none', 'Aucune'), ('api_key', 'Clé API'), ('bearer', 'Bearer token'), ('basic', 'Basic auth'), ('oauth2', 'OAuth2'), ('header', 'Header personnalisé')], default='none', max_length=16)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Headers HTTP personnalisés (non secrets).')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Config spécifique : host/port/dbname, file_path, sheet_id, airbyte_connection_id…')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(null=True)),
                ('last_test_message', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectorEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('path', models.CharField(blank=True, help_text='Chemin relatif / table / nom de feuille / requête.', max_length=500)),
                ('http_method', models.CharField(default='GET', max_length=8)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('incremental', models.BooleanField(default=False)),
                ('cursor_field', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='integrations.dataconnector')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('api_token', 'Token API'), ('api_key', 'Clé API'), ('client_id', 'Client ID'), ('client_secret', 'Client Secret'), ('password', 'Mot de passe'), ('oauth_refresh', 'OAuth refresh token')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('secret_ciphertext', models.TextField(blank=True, default='')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='integrations.dataconnector')),
            ],
            options={
                'verbose_name': 'Identifiant chiffré',
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('source_type', models.CharField(choices=[('rest', 'API REST'), ('graphql', 'API GraphQL'), ('webhook', 'Webhook'), ('postgres', 'PostgreSQL (lecture seule)'), ('mysql', 'MySQL (lecture seule)'), ('csv', 'Fichier CSV'), ('excel', 'Excel'), ('gsheets', 'Google Sheets'), ('airbyte', 'Connecteur Airbyte')], max_length=16)),
                ('target_module', models.CharField(choices=[('rh', 'Capital Humain'), ('immobilier', 'Immobilier'), ('finance', 'Finance'), ('stocks', 'Stocks & Logistique'), ('flotte', 'Flotte'), ('securite', 'Sécurité'), ('commercial', 'Commercial & Clients'), ('risques', 'Risques & Conformité'), ('groupe', 'Groupe / Transverse'), ('autre', 'Autre')], default='autre', max_length=16)),
                ('status', models.CharField(choices=[('not_configured', 'Non configurée'), ('configured', 'Configurée'), ('testing', 'En test'), ('connected', 'Connectée'), ('syncing', 'Synchronisation en cours'), ('error', 'Erreur'), ('disabled', 'Désactivée')], default='not_configured', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('demo_mode', models.BooleanField(default=False, help_text='Mode dégradé : afficher des données de démonstration tant que non connectée.')),
                ('sync_frequency', models.CharField(blank=True, default='manual', help_text="cron ou 'manual'", max_length=64)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Source de données',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dataconnector',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connector', to='integrations.datasource'),
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_field', models.CharField(max_length=200)),
                ('target_field', models.CharField(max_length=200)),
                ('target_table', models.CharField(blank=True, max_length=200)),
                ('transform', models.CharField(blank=True, help_text='Transformation optionnelle (ex. to_int, trim, date).', max_length=200)),
                ('is_key', models.BooleanField(default=False)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='integrations.connectorendpoint')),
            ],
            options={
                'ordering': ['source_field'],
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('manual', 'Manuelle'), ('scheduled', 'Planifiée'), ('webhook', 'Webhook')], default='manual', max_length=12)),
                ('status', models.CharField(choices=[('queued', 'En file'), ('running', 'En cours'), ('success', 'Succès'), ('partial', 'Partielle'), ('error', 'Erreur')], default='queued', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows_ingested', models.PositiveIntegerField(default=0)),
                ('incremental', models.BooleanField(default=False)),
                ('cursor_value', models.CharField(blank=True, max_length=200)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='integrations.datasource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='integrations.datasource')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='integrations.syncjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warn', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=8)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.syncjob')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.datasource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('signature_valid', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='integrations.datasource')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
