# Generated by Django 6.0.4 on 2026-08-24 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('employee', 'Employé'), ('worker', 'Ouvrier'), ('other', 'Autre')], default='other', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Personne',
                'ordering': ['display_name'],
            },
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('rest', 'API REST'), ('graphql', 'API GraphQL'), ('webhook', 'Webhook'), ('postgres', 'PostgreSQL (lecture seule)'), ('mysql', 'MySQL (lecture seule)'), ('csv', 'Fichier CSV'), ('excel', 'Excel'), ('gsheets', 'Google Sheets'), ('airbyte', 'Connecteur Airbyte'), ('kaydan_shield', "Kaydan Shield (contrôle d'accès / RH)"), ('odoo_hr', 'Odoo RH')], max_length=16),
        ),
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(help_text="Code source, ex. 'kaydan_shield'.", max_length=32)),
                ('external_id', models.CharField(max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Snapshot brut non normalisé (audit).')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='integrations.person')),
            ],
            options={
                'verbose_name': 'Identité externe',
                'ordering': ['source', 'external_id'],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_source_external_id')],
            },
        ),
    ]
