# Generated by Django 6.0.4 on 2026-09-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_person_alter_datasource_source_type_externalidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnector',
            name='last_latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='environment',
            field=models.CharField(choices=[('production', 'Production'), ('staging', 'Recette'), ('sandbox', 'Bac à sable')], default='production', max_length=12),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('rest', 'API REST'), ('graphql', 'API GraphQL'), ('webhook', 'Webhook'), ('postgres', 'PostgreSQL (lecture seule)'), ('mysql', 'MySQL (lecture seule)'), ('csv', 'Fichier CSV'), ('excel', 'Excel'), ('gsheets', 'Google Sheets'), ('airbyte', 'Connecteur Airbyte'), ('kaydan_shield', "Kaydan Shield (contrôle d'accès / RH)"), ('odoo_hr', 'Odoo RH'), ('sap', 'SAP'), ('edw', 'Entrepôt de données (mart)')], max_length=16),
        ),
    ]
