# Generated by Django 6.0.4 on 2026-09-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_dataconnector_last_latency_ms_datasource_environment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='demo_mode',
            field=models.BooleanField(default=False, help_text='Mode dégradé, désactivé par défaut : une source non connectée doit afficher son état, jamais des données simulées.'),
        ),
    ]
