# Generated by Django 6.0.4 on 2026-09-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_alter_datasource_demo_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectorcredential',
            options={'verbose_name': 'Identifiant chiffré', 'verbose_name_plural': 'Identifiants chiffrés'},
        ),
        migrations.AlterModelOptions(
            name='connectorendpoint',
            options={'ordering': ['name'], 'verbose_name': 'Endpoint', 'verbose_name_plural': 'Endpoints'},
        ),
        migrations.AlterModelOptions(
            name='dataconnector',
            options={'verbose_name': 'Connecteur', 'verbose_name_plural': 'Connecteurs'},
        ),
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ['name'], 'verbose_name': 'Source de données', 'verbose_name_plural': 'Sources de données'},
        ),
        migrations.AlterModelOptions(
            name='externalidentity',
            options={'ordering': ['source', 'external_id'], 'verbose_name': 'Identité externe', 'verbose_name_plural': 'Identités externes'},
        ),
        migrations.AlterModelOptions(
            name='fieldmapping',
            options={'ordering': ['source_field'], 'verbose_name': 'Correspondance de champs', 'verbose_name_plural': 'Correspondances de champs'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['display_name'], 'verbose_name': 'Personne', 'verbose_name_plural': 'Personnes'},
        ),
        migrations.AlterModelOptions(
            name='syncerror',
            options={'ordering': ['-created_at'], 'verbose_name': 'Erreur de synchronisation', 'verbose_name_plural': 'Erreurs de synchronisation'},
        ),
        migrations.AlterModelOptions(
            name='syncjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Synchronisation', 'verbose_name_plural': 'Synchronisations'},
        ),
        migrations.AlterModelOptions(
            name='synclog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Journal de synchronisation', 'verbose_name_plural': 'Journaux de synchronisation'},
        ),
        migrations.AlterModelOptions(
            name='webhookevent',
            options={'ordering': ['-received_at'], 'verbose_name': 'Événement webhook', 'verbose_name_plural': 'Événements webhook'},
        ),
    ]
