# Generated by Django 6.0.4 on 2026-06-27 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_copilot', '0002_aiactionrequest_destructive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aiactionapproval',
            constraint=models.UniqueConstraint(fields=('request', 'approver'), name='uniq_approval_per_user'),
        ),
    ]
