# Generated by Django 6.0.4 on 2026-09-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_copilot', '0003_aiactionapproval_uniq_approval_per_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiactionapproval',
            options={'verbose_name': "Approbation d'action", 'verbose_name_plural': "Approbations d'action"},
        ),
        migrations.AlterModelOptions(
            name='aiactionrequest',
            options={'ordering': ['-created_at'], 'verbose_name': "Demande d'action sensible", 'verbose_name_plural': "Demandes d'action sensible"},
        ),
        migrations.AlterModelOptions(
            name='aiauditlog',
            options={'ordering': ['-occurred_at'], 'verbose_name': "Journal d'audit IA", 'verbose_name_plural': "Journaux d'audit IA"},
        ),
        migrations.AlterModelOptions(
            name='aiautomation',
            options={'ordering': ['name'], 'verbose_name': 'Automatisation du Copilot', 'verbose_name_plural': 'Automatisations du Copilot'},
        ),
        migrations.AlterModelOptions(
            name='aiconversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Conversation Copilot', 'verbose_name_plural': 'Conversations Copilot'},
        ),
        migrations.AlterModelOptions(
            name='aimessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Message Copilot', 'verbose_name_plural': 'Messages Copilot'},
        ),
        migrations.AlterModelOptions(
            name='aiprovider',
            options={'ordering': ['priority'], 'verbose_name': 'Moteur LLM', 'verbose_name_plural': 'Moteurs LLM'},
        ),
        migrations.AlterModelOptions(
            name='aitool',
            options={'verbose_name': "Outil exposé à l'IA", 'verbose_name_plural': "Outils exposés à l'IA"},
        ),
        migrations.AlterModelOptions(
            name='aitoolexecution',
            options={'ordering': ['-created_at'], 'verbose_name': "Exécution d'outil", 'verbose_name_plural': "Exécutions d'outils"},
        ),
    ]
