# Generated by Django 6.0.4 on 2026-06-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('entity_code', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(default='CI', max_length=2)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Filiale',
                'verbose_name_plural': 'Filiales',
                'ordering': ['code'],
            },
        ),
    ]
